# Generated by Django 5.0.6 on 2024-06-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_numbers_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('numero_Pokedex', models.IntegerField()),
                ('tipo_primario', models.CharField(max_length=15)),
                ('tipo_secundario', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
